### ISSUE TITLE
makemigrations core error

### ISSUE THREAD

**Issue by Djangostudent** [tomaratyn/MyMDB#1]
Hi! I came to the point of migrating the core database with:
python manage.py makemigrations core
but I cant get past this error: 
``Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/master/alanenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/master/alanenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/master/alanenv/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/master/alanenv/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/master/alanenv/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/master/alanenv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/master/MyMDB/django/core/models.py", line 1
    from django.db import import models"

Now Im stuck and the following:
python manage.py migrate core 
command is also not working.

Who can help me out with a hint of what the problem is? 
Im new to django/python but Im trying to learn as much as I can. I would be even happy with searchtags for google so i can look it up. I'm trying now for hours but sadly I cant find a solution. 

Greetings

**Comment by Djangostudent** [comment]
I found the mistake(s). Had some typo-errors in my models.py file. 
If anybody has the same problem, try checking for typo errors. 
Greetings
